[2025-08-14 19:26:03] [INFO] [main.py:67] - Запуск приложения: инициализация БД
[2025-08-14 19:26:03] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-14 19:26:03] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-14 19:26:03] [INFO] [main.py:69] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-14 19:26:03] [INFO] [main.py:96] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-14 19:46:39] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-14 19:46:39] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-14 19:46:39] [ERROR] [database.py:57] - Ошибка в контексте сессии: name 'Transaction' is not defined
[2025-08-14 19:46:39] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-14 19:48:54] [INFO] [main.py:102] - Планировщик остановлен
[2025-08-14 19:49:08] [INFO] [main.py:67] - Запуск приложения: инициализация БД
[2025-08-14 19:49:08] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-14 19:49:08] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-14 19:49:08] [INFO] [main.py:69] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-14 19:49:08] [INFO] [main.py:96] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-14 19:49:29] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-14 19:49:29] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-14 19:49:29] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-14 19:50:07] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-14 19:50:07] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-14 19:50:07] [INFO] [database.py:60] - Закрытие сессии с БД.
